In [3]:
%pip install pandas

Requirement already satisfied: pandas in c:\genai\.venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\genai\.venv\lib\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\genai\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\genai\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\genai\.venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\genai\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import os
import pandas as pd

In [5]:
data=pd.read_csv("https://raw.githubusercontent.com/Ankit152/IMDB-sentiment-analysis/master/IMDB-Dataset.csv")

In [6]:
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [7]:
data.tail()

                                                  review sentiment
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

In [8]:
data.sample(5)

                                                  review sentiment
24567  an very good storyline, good thrill to it ... ...  negative
39951  Here we have 2 misunderstood kids who never st...  negative
1016   Jackass Number Two is easily the most hilariou...  positive
38624  A movie/documentary about different people in ...  positive
37346  I just came back from Hong Kong on my summer v...  positive

In [9]:
data["review"][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [10]:
data["review"][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [11]:
data.shape

(50000, 2)

In [12]:
data["review"].str.lower()

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [13]:
import re

In [14]:
def remove_html_tags(text):
    pattern=re.compile('<.*?>')
    return pattern.sub("",text)

In [15]:
text="""<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Welcome to My Website</title><style>body{font-family:'Arial',sans-serif;background-color:#f0f0f0;color:#333;margin:20px}h1{color:#007bff}p{line-height:1.5}</style></head><body><header><h1>Welcome to My Awesome Website!</h1></header><main><p>This is a sample HTML document created for demonstration purposes.</p><p>Feel free to explore and enjoy the content on this website.</p></main><footer><p>&copy; 2024 My Website. All rights reserved.</p></footer></body></html>"""

In [16]:
text

'<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Welcome to My Website</title><style>body{font-family:\'Arial\',sans-serif;background-color:#f0f0f0;color:#333;margin:20px}h1{color:#007bff}p{line-height:1.5}</style></head><body><header><h1>Welcome to My Awesome Website!</h1></header><main><p>This is a sample HTML document created for demonstration purposes.</p><p>Feel free to explore and enjoy the content on this website.</p></main><footer><p>&copy; 2024 My Website. All rights reserved.</p></footer></body></html>'

In [17]:
remove_html_tags(text)

"Welcome to My Websitebody{font-family:'Arial',sans-serif;background-color:#f0f0f0;color:#333;margin:20px}h1{color:#007bff}p{line-height:1.5}Welcome to My Awesome Website!This is a sample HTML document created for demonstration purposes.Feel free to explore and enjoy the content on this website.&copy; 2024 My Website. All rights reserved."

In [18]:
data["review"].apply(remove_html_tags)

0        One of the other reviewers has mentioned that ...
1        A wonderful little production. The filming tec...
2        I thought this was a wonderful way to spend ti...
3        Basically there's a family where a little boy ...
4        Petter Mattei's "Love in the Time of Money" is...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot, bad dialogue, bad acting, idiotic di...
49997    I am a Catholic taught in parochial elementary...
49998    I'm going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: object

In [19]:
def remove_url(text):
    pattern=re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub("",text)

In [20]:
text1="checkout to my youtube channel https://www.youtube.com/watch?v=V9tJCQoBakA&t=225s"
text2="please try to google here www.google.com"
text3="here is my url which is not secure http://dummy.com"

In [21]:
remove_url(text2)

'please try to google here '

In [22]:
%pip install string

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement string (from versions: none)
ERROR: No matching distribution found for string

In [23]:
import string

In [24]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [25]:
exclude=string.punctuation

In [26]:
for char in exclude:
    print(char)

!
"
#
$
%
&
'
(
)
*
+
,
-
.
/
:
;
<
=
>
?
@
[
\
]
^
_
`
{
|
}
~

In [27]:
def remove_punc(text):
    for char in exclude:
        text=text.replace(char,"")
    return text

In [28]:
remove_punc(text)

'DOCTYPE htmlhtml langenheadmeta charsetUTF8meta httpequivXUACompatible contentIEedgemeta nameviewport contentwidthdevicewidth initialscale10titleWelcome to My WebsitetitlestylebodyfontfamilyArialsansserifbackgroundcolorf0f0f0color333margin20pxh1color007bffplineheight15styleheadbodyheaderh1Welcome to My Awesome Websiteh1headermainpThis is a sample HTML document created for demonstration purposesppFeel free to explore and enjoy the content on this websitepmainfooterpcopy 2024 My Website All rights reservedpfooterbodyhtml'

In [29]:
text2="my name is s@nny sa##vita!!!!!!!!!"

In [30]:
remove_punc(text2)

'my name is snny savita'

In [31]:
def remove_punc1(text):
    return text.translate(str.maketrans("","",exclude))

In [32]:
data["review"]=data["review"].apply(remove_punc)

In [33]:
text ="FYI this is not true"
text2="LAMO the class was so funny"
text3="i want report ASAP"

In [34]:
chat_words={
    " AFAIK":"As Far As I Know",
    "AFK": "Away From Keyboard",
    "ASAP":"As Soon As Possible",
    "BTW":"By The Way",
    "B4":"Before",
    "LAMO":"Laugh My A.. Off",
    "FYI":"For your information"
}

In [35]:
def chat_conversion(text):
    new_text=[]
    for w in text.split():
        if w.upper() in chat_words:
           new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [36]:
chat_conversion(text)

'For your information this is not true'

In [37]:
# spell correction
text = "I amm good at speling"

In [38]:
# text1 =" Brav and  strong"

In [39]:
!pip install textblob

Requirement already satisfied: textblob in c:\genai\.venv\lib\site-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in c:\genai\.venv\lib\site-packages (from textblob) (3.9.2)
Requirement already satisfied: click in c:\genai\.venv\lib\site-packages (from nltk>=3.9->textblob) (8.3.1)
Requirement already satisfied: joblib in c:\genai\.venv\lib\site-packages (from nltk>=3.9->textblob) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\genai\.venv\lib\site-packages (from nltk>=3.9->textblob) (2025.11.3)
Requirement already satisfied: tqdm in c:\genai\.venv\lib\site-packages (from nltk>=3.9->textblob) (4.67.1)
Requirement already satisfied: colorama in c:\genai\.venv\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)

In [40]:
from textblob import TextBlob
txtblob=TextBlob(text)
txtblob.correct().string

'I am good at spelling'

In [41]:
#correct method not work for all --(70% accuracy)

# txtblob1=TextBlob(text1)
# txtblob1.correct().string

In [42]:

# instead use suggest method
text1 =" Brave and  strong"
from textblob import TextBlob
txtblob1=TextBlob(text1)
txtblob1.correct().string

' Grave and  strong'

In [43]:
# remove stopwords ...word which not play role in that thing

In [44]:
!pip install nltk

Requirement already satisfied: nltk in c:\genai\.venv\lib\site-packages (3.9.2)
Requirement already satisfied: click in c:\genai\.venv\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\genai\.venv\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\genai\.venv\lib\site-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in c:\genai\.venv\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\genai\.venv\lib\site-packages (from click->nltk) (0.4.6)

In [45]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\urmi1506\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [46]:
stopwords.words("english")

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [47]:
def remove_stopwords(text):
    new_text=[]

    for word in text.split():
        if word in stopwords.words("english"):
            continue

        else:
            new_text.append(word)

    return " ".join(new_text)

In [48]:
text = "i am urmi and we are learning nlp and here is why nlp is important"
print(text)

i am urmi and we are learning nlp and here is why nlp is important

In [49]:
remove_stopwords(text)

'urmi learning nlp nlp important'

In [50]:
# remove emoji

In [51]:
!pip install emoji

Requirement already satisfied: emoji in c:\genai\.venv\lib\site-packages (2.15.0)

In [52]:
import emoji

original_text = "Hello,😊 how are you today? 🌟"

def remove_emoji(text):
    clean_text=emoji.demojize(text)
    return clean_text
remove_emoji(original_text)

'Hello,:smiling_face_with_smiling_eyes: how are you today? :glowing_star:'

In [53]:
print(emoji.is_emoji("👍"))

True

In [54]:
print(emoji.is_emoji("thumb up"))

False

In [55]:
text_emj1="""Hello, 😃💁😃💁 People
•🐻🌻 Animals
•🍔🍹 Food
•🎷⚽ Activities
•🚘🌇 Travel
•💡🎉 Objects
•💖🔣 Symbols
•🎌🏳️‍🌈 Flags"""

print(remove_emoji(text_emj1))

Hello, :grinning_face_with_big_eyes::person_tipping_hand::grinning_face_with_big_eyes::person_tipping_hand: People
•:bear::sunflower: Animals
•:hamburger::tropical_drink: Food
•:saxophone::soccer_ball: Activities
•:oncoming_automobile::sunset: Travel
•:light_bulb::party_popper: Objects
•:sparkling_heart::input_symbols: Symbols
•:crossed_flags::rainbow_flag: Flags

In [56]:
text4="""
🌟 "Hello there! Hope your day is as bright as the stars!"
🌈 "Wishing you a colorful and joyful day ahead!"
🌸 "Sending you virtual flowers to brighten your day!"
🎉 "Celebrate every small victory! You deserve it!"
🤗 "Virtual hug coming your way! You're not alone."
🌞 "Rise and shine! Make today amazing!"
🍀 "Good luck on your endeavors! You've got this!"
🎈 "Life is a party! Enjoy every moment!"
📚 "Study hard and ace those exams! You're brilliant!"
🚀 "Soar high and reach for the stars in all you do!"

"""

print(remove_emoji(text4))

:glowing_star: "Hello there! Hope your day is as bright as the stars!"
:rainbow: "Wishing you a colorful and joyful day ahead!"
:cherry_blossom: "Sending you virtual flowers to brighten your day!"
:party_popper: "Celebrate every small victory! You deserve it!"
:smiling_face_with_open_hands: "Virtual hug coming your way! You're not alone."
:sun_with_face: "Rise and shine! Make today amazing!"
:four_leaf_clover: "Good luck on your endeavors! You've got this!"
:balloon: "Life is a party! Enjoy every moment!"
:books: "Study hard and ace those exams! You're brilliant!"
:rocket: "Soar high and reach for the stars in all you do!"

In [58]:
import re
def remove_emojis_manually(text):
    emoji_pattern = re.compile("["
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                               u"\U0001F680-\U0001F6FF"  # transport & map symbols
                               u"\U0001F700-\U0001F77F"  # alchemical symbols
                               u"\U0001F780-\U0001F7FF"  # Geometric Shapes Extended
                               u"\U0001F800-\U0001F8FF"  # Supplemental Arrows-C
                               u"\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
                               u"\U0001FA00-\U0001FA6F"  # Chess Symbols
                               u"\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
                               u"\U00002702-\U000027B0"  # Dingbats
                               u"\U000024C2-\U0001F251" 
                               "]+", flags=re.UNICODE)
    clean_text = emoji_pattern.sub(r'', text)
    return clean_text

print(remove_emojis_manually(text4))

 "Hello there! Hope your day is as bright as the stars!"
 "Wishing you a colorful and joyful day ahead!"
 "Sending you virtual flowers to brighten your day!"
 "Celebrate every small victory! You deserve it!"
 "Virtual hug coming your way! You're not alone."
 "Rise and shine! Make today amazing!"
 "Good luck on your endeavors! You've got this!"
 "Life is a party! Enjoy every moment!"
 "Study hard and ace those exams! You're brilliant!"
 "Soar high and reach for the stars in all you do!"

In [59]:
print(remove_emojis_manually(original_text))

Hello, how are you today?

In [ ]:
# Tokenization
# convert text into word ....word Tokenization
# sentence (document) Tokenization

In [60]:
text="i am urmi and working as a data scientist. i live in banglore. i work in ineuron ai devlopment team"

In [62]:
text.split(".")

['i am urmi and working as a data scientist',
 ' i live in banglore',
 ' i work in ineuron ai devlopment team']

In [65]:
text3 ="i live in Pune!!"
text3.split()

['i', 'live', 'in', 'Pune!!']

In [66]:
text4="where should i go? i habve 3 days hoilidays, Can you sugguest me?"
text4.split(".")

['where should i go? i habve 3 days hoilidays, Can you sugguest me?']

In [ ]:
# if split() not working then use regular expression
import re
text3="i live in bangalore!!"

In [68]:
re.findall("[\w]+",text3)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
C:\Users\urmi1506\AppData\Local\Temp\ipykernel_2004\2995268902.py:1: SyntaxWarning: invalid escape sequence '\w'
  re.findall("[\w]+",text3)

['i', 'live', 'in', 'bangalore']

In [70]:
import nltk

In [71]:
from nltk.tokenize import word_tokenize,sent_tokenize

my_text="i am going to visit delhi tomorrow evening"

word_tokenize(my_text)

['i', 'am', 'going', 'to', 'visit', 'delhi', 'tomorrow', 'evening']

In [72]:
my_text="i am going to visit delhi tomorrow evening!!!!"

word_tokenize(my_text)

['i',
 'am',
 'going',
 'to',
 'visit',
 'delhi',
 'tomorrow',
 'evening',
 '!',
 '!',
 '!',
 '!']

In [74]:
my_corpus="""Generative artificial intelligence (generative AI, genAI, GenAI, GAI or GenAI[1]) is artificial intelligence capable of generating text, images or other data using generative models,[2] often in response to prompts.[3][4] Generative AI models learn the patterns and structure of their input training data and then generate new data that has similar characteristics.[5][6]

Improvements in transformer-based deep neural networks enabled an AI boom of generative AI systems in the early 2020s. These include large language model (LLM) chatbots such as ChatGPT, Copilot, Bard, and LLaMA, and text-to-image artificial intelligence art systems such as Stable Diffusion, Midjourney, and DALL-E.[7][8][9] Companies such as OpenAI, Anthropic, Microsoft, Google, and Baidu as well as numerous smaller firms have developed generative AI models.[3][10][11]"""

sent_tokenize(my_corpus)

['Generative artificial intelligence (generative AI, genAI, GenAI, GAI or GenAI[1]) is artificial intelligence capable of generating text, images or other data using generative models,[2] often in response to prompts.',
 '[3][4] Generative AI models learn the patterns and structure of their input training data and then generate new data that has similar characteristics.',
 '[5][6]\n\nImprovements in transformer-based deep neural networks enabled an AI boom of generative AI systems in the early 2020s.',
 'These include large language model (LLM) chatbots such as ChatGPT, Copilot, Bard, and LLaMA, and text-to-image artificial intelligence art systems such as Stable Diffusion, Midjourney, and DALL-E.[7][8][9] Companies such as OpenAI, Anthropic, Microsoft, Google, and Baidu as well as numerous smaller firms have developed generative AI models.',
 '[3][10][11]']

In [ ]:
# we can do it by using nltk and even with spacy

# split
# regular expression(simple google)
# nltk

In [75]:
!pip install spacy

Collecting spacy
  Using cached spacy-3.8.11-cp312-cp312-win_amd64.whl.metadata (28 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Using cached spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Using cached murmurhash-1.0.15-cp312-cp312-win_amd64.whl.metadata (2.3 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Using cached cymem-2.0.13-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Using cached preshed-3.0.12-cp312-cp312-win_amd64.whl.metadata (2.6 kB)
Collecting thinc<8.4.0,>=8.3.4 (from spacy)
  Using cached thinc-8.3.10-cp312-cp312-win_amd64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Using cached wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.4.3 (from spacy)
  Using cached srsly-2.5.2-cp312-cp312-win_amd64.whl.metadata (20 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Using cached catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<0.5.0,>=0.4.2 (from spacy)
  Using cached weasel-0.4.3-py3-none-any.whl.metadata (4.6 kB)
Collecting typer-slim<1.0.0,>=0.3.0 (from spacy)
  Downloading typer_slim-0.24.0-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\genai\.venv\lib\site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in c:\genai\.venv\lib\site-packages (from spacy) (2.4.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\genai\.venv\lib\site-packages (from spacy) (2.32.5)
Collecting pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 (from spacy)
  Using cached pydantic-2.12.5-py3-none-any.whl.metadata (90 kB)
Requirement already satisfied: jinja2 in c:\genai\.venv\lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in c:\genai\.venv\lib\site-packages (from spacy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in c:\genai\.venv\lib\site-packages (from spacy) (25.0)
Collecting annotated-types>=0.6.0 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.5 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Using cached pydantic_core-2.41.5-cp312-cp312-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\genai\.venv\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Collecting typing-inspection>=0.4.2 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\genai\.venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\genai\.venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\genai\.venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\genai\.venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.1.4)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.4->spacy)
  Using cached blis-1.3.3-cp312-cp312-win_amd64.whl.metadata (7.7 kB)
Collecting confection<1.0.0,>=0.0.1 (from thinc<8.4.0,>=8.3.4->spacy)
  Using cached confection-0.1.5-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: colorama in c:\genai\.venv\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Collecting typer>=0.24.0 (from typer-slim<1.0.0,>=0.3.0->spacy)
  Downloading typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Collecting cloudpathlib<1.0.0,>=0.7.0 (from weasel<0.5.0,>=0.4.2->spacy)
  Using cached cloudpathlib-0.23.0-py3-none-any.whl.metadata (16 kB)
Collecting smart-open<8.0.0,>=5.2.1 (from weasel<0.5.0,>=0.4.2->spacy)
  Downloading smart_open-7.5.1-py3-none-any.whl.metadata (24 kB)
Collecting wrapt (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy)
  Downloading wrapt-2.1.1-cp312-cp312-win_amd64.whl.metadata (7.6 kB)
Requirement already satisfied: click>=8.2.1 in c:\genai\.venv\lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (8.3.1)
Collecting shellingham>=1.3.0 (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=12.3.0 (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy)
  Downloading rich-14.3.3-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy)
  Using cached markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\genai\.venv\lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.19.2)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\genai\.venv\lib\site-packages (from jinja2->spacy) (3.0.3)
Using cached spacy-3.8.11-cp312-cp312-win_amd64.whl (14.2 MB)
Using cached catalogue-2.0.10-py3-none-any.whl (17 kB)
Using cached cymem-2.0.13-cp312-cp312-win_amd64.whl (40 kB)
Using cached murmurhash-1.0.15-cp312-cp312-win_amd64.whl (25 kB)
Using cached preshed-3.0.12-cp312-cp312-win_amd64.whl (118 kB)
Using cached pydantic-2.12.5-py3-none-any.whl (463 kB)
Using cached pydantic_core-2.41.5-cp312-cp312-win_amd64.whl (2.0 MB)
Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Using cached spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Using cached srsly-2.5.2-cp312-cp312-win_amd64.whl (654 kB)
Using cached thinc-8.3.10-cp312-cp312-win_amd64.whl (1.7 MB)
Using cached blis-1.3.3-cp312-cp312-win_amd64.whl (6.2 MB)
Using cached confection-0.1.5-py3-none-any.whl (35 kB)
Downloading typer_slim-0.24.0-py3-none-any.whl (3.4 kB)
Using cached wasabi-1.1.3-py3-none-any.whl (27 kB)
Using cached weasel-0.4.3-py3-none-any.whl (50 kB)
Using cached cloudpathlib-0.23.0-py3-none-any.whl (62 kB)
Downloading smart_open-7.5.1-py3-none-any.whl (64 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading typer-0.24.1-py3-none-any.whl (56 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading rich-14.3.3-py3-none-any.whl (310 kB)
Using cached markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Downloading wrapt-2.1.1-cp312-cp312-win_amd64.whl (60 kB)
Installing collected packages: wrapt, wasabi, typing-inspection, spacy-loggers, spacy-legacy, shellingham, pydantic-core, murmurhash, mdurl, cymem, cloudpathlib, catalogue, blis, annotated-types, annotated-doc, srsly, smart-open, pydantic, preshed, markdown-it-py, rich, confection, typer, thinc, typer-slim, weasel, spacy

   ----------------------------------------  0/27 [wrapt]
   - --------------------------------------  1/27 [wasabi]
   - --------------------------------------  1/27 [wasabi]
   -- -------------------------------------  2/27 [typing-inspection]
   ---- -----------------------------------  3/27 [spacy-loggers]
   ----- ----------------------------------  4/27 [spacy-legacy]
   ----- ----------------------------------  4/27 [spacy-legacy]
   ----- ----------------------------------  4/27 [spacy-legacy]
   -------- -------------------------------  6/27 [pydantic-core]
   ---------- -----------------------------  7/27 [murmurhash]
   ------------- --------------------------  9/27 [cymem]
   -------------- ------------------------- 10/27 [cloudpathlib]
   -------------- ------------------------- 10/27 [cloudpathlib]
   -------------- ------------------------- 10/27 [cloudpathlib]
   -------------- ------------------------- 10/27 [cloudpathlib]
   ----------------- ---------------------- 12/27 [blis]
   ----------------- ---------------------- 12/27 [blis]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ---------------------- ----------------- 15/27 [srsly]
   ----------------------- ---------------- 16/27 [smart-open]
   ----------------------- ---------------- 16/27 [smart-open]
   ----------------------- ---------------- 16/27 [smart-open]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   ------------------------- -------------- 17/27 [pydantic]
   -------------------------- ------------- 18/27 [preshed]
   ---------------------------- ----------- 19/27 [markdown-it-py]
   ---------------------------- ----------- 19/27 [markdown-it-py]
   ---------------------------- ----------- 19/27 [markdown-it-py]
   ---------------------------- ----------- 19/27 [markdown-it-py]
   ---------------------------- ----------- 19/27 [markdown-it-py]
   ---------------------------- ----------- 19/27 [markdown-it-py]
   ---------------------------- ----------- 19/27 [markdown-it-py]
   ---------------------------- ----------- 19/27 [markdown-it-py]
   ---------------------------- ----------- 19/27 [markdown-it-py]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ----------------------------- ---------- 20/27 [rich]
   ------------------------------- -------- 21/27 [confection]
   ------------------------------- -------- 21/27 [confection]
   -------------------------------- ------- 22/27 [typer]
   -------------------------------- ------- 22/27 [typer]
   -------------------------------- ------- 22/27 [typer]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ---------------------------------- ----- 23/27 [thinc]
   ------------------------------------- -- 25/27 [weasel]
   ------------------------------------- -- 25/27 [weasel]
   ------------------------------------- -- 25/27 [weasel]
   ------------------------------------- -- 25/27 [weasel]
   ------------------------------------- -- 25/27 [weasel]
   ------------------------------------- -- 25/27 [weasel]
   ------------------------------------- -- 25/27 [weasel]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]
   -------------------------------------- - 26/27 [spacy]

In [78]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---- ----------------------------------- 1.6/12.8 MB 7.6 MB/s eta 0:00:02
     ------------- -------------------------- 4.2/12.8 MB 10.5 MB/s eta 0:00:01
     ---------------- ----------------------- 5.2/12.8 MB 11.4 MB/s eta 0:00:01
     -------------------- ------------------- 6.6/12.8 MB 8.0 MB/s eta 0:00:01
     ---------------------- ----------------- 7.1/12.8 MB 6.9 MB/s eta 0:00:01
     --------------------------- ------------ 8.7/12.8 MB 7.1 MB/s eta 0:00:01
     ------------------------------- -------- 10.0/12.8 MB 7.0 MB/s eta 0:00:01
     ----------------------------------- ---- 11.3/12.8 MB 6.9 MB/s eta 0:00:01
     ------------------------------------ --- 11.8/12.8 MB 6.4 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 6.6 MB/s  0:00:01
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [79]:
import spacy

# Load the English NLP model from spacy
nlp = spacy.load("en_core_web_sm")

def tokenize_text(text):
    # Process the text with the spacy model
    doc = nlp(text)
    
    # Extract tokens from the processed document
    tokens = [token.text for token in doc]
    
    return tokens

tokens=tokenize_text(my_corpus)

for word in tokens:
    print(word)

Generative
artificial
intelligence
(
generative
AI
,
genAI
,
GenAI
,
GAI
or
GenAI[1
]
)
is
artificial
intelligence
capable
of
generating
text
,
images
or
other
data
using
generative
models,[2
]
often
in
response
to
prompts.[3][4
]
Generative
AI
models
learn
the
patterns
and
structure
of
their
input
training
data
and
then
generate
new
data
that
has
similar
characteristics.[5][6
]



Improvements
in
transformer
-
based
deep
neural
networks
enabled
an
AI
boom
of
generative
AI
systems
in
the
early
2020s
.
These
include
large
language
model
(
LLM
)
chatbots
such
as
ChatGPT
,
Copilot
,
Bard
,
and
LLaMA
,
and
text
-
to
-
image
artificial
intelligence
art
systems
such
as
Stable
Diffusion
,
Midjourney
,
and
DALL
-
E.[7][8][9
]
Companies
such
as
OpenAI
,
Anthropic
,
Microsoft
,
Google
,
and
Baidu
as
well
as
numerous
smaller
firms
have
developed
generative
AI
models.[3][10][11
]

In [80]:
string1 = "This is the first sentence. This is the second sentence. This is the third sentence."
doc = nlp(string1)

for sent in doc.sents:
    print(sent)

This is the first sentence.
This is the second sentence.
This is the third sentence.

In [81]:
text = "Spacy is a powerful natural language processing library."
tokens = tokenize_text(text)

print(f"Original text: {text}")
print(f"Tokens: {tokens}")

Original text: Spacy is a powerful natural language processing library.
Tokens: ['Spacy', 'is', 'a', 'powerful', 'natural', 'language', 'processing', 'library', '.']

In [ ]:
# stemming and lemmetization

In [83]:
from nltk.stem import PorterStemmer

def stemming(text):
    obj=PorterStemmer()

    stem_word=[obj.stem(word) for word in text.split()]

    return stem_word

stemming(text)

['spaci', 'is', 'a', 'power', 'natur', 'languag', 'process', 'library.']

In [84]:
text = "I am worked in JPMorgan and then I am working in microsoft "

stemming(text)

['i',
 'am',
 'work',
 'in',
 'jpmorgan',
 'and',
 'then',
 'i',
 'am',
 'work',
 'in',
 'microsoft']

In [85]:
input_sentence = "The quick brown foxes are jumping over the lazy dogs"

stemming(input_sentence)

['the', 'quick', 'brown', 'fox', 'are', 'jump', 'over', 'the', 'lazi', 'dog']

In [86]:
from nltk.stem import WordNetLemmatizer

def lammatization(text):
    words=text.split()

    lemmetizer=WordNetLemmatizer()

    lemetized_word=[lemmetizer.lemmatize(word) for word in words]
    
    return lemetized_word

input_sentence = "The quick brown foxes are jumping over the lazy dogs"

lammatization(input_sentence)

['The',
 'quick',
 'brown',
 'fox',
 'are',
 'jumping',
 'over',
 'the',
 'lazy',
 'dog']

In [87]:
text="'Ikigai' by Hector Garcia and Francesc Miralles explores the Japanese concept of finding one's purpose in life by analyzing the habits and beliefs of the world's longest-living people. Through case studies, the book offers practical insights on how to live a more fulfilling life."

lammatization(text)

["'Ikigai'",
 'by',
 'Hector',
 'Garcia',
 'and',
 'Francesc',
 'Miralles',
 'explores',
 'the',
 'Japanese',
 'concept',
 'of',
 'finding',
 "one's",
 'purpose',
 'in',
 'life',
 'by',
 'analyzing',
 'the',
 'habit',
 'and',
 'belief',
 'of',
 'the',
 "world's",
 'longest-living',
 'people.',
 'Through',
 'case',
 'studies,',
 'the',
 'book',
 'offer',
 'practical',
 'insight',
 'on',
 'how',
 'to',
 'live',
 'a',
 'more',
 'fulfilling',
 'life.']